# Generated by Django 5.2.6 on 2025-09-16 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('read', models.BooleanField(default=False, verbose_name='Lida')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Empresa')),
                ('position', models.CharField(max_length=200, verbose_name='Cargo')),
                ('description', models.TextField(verbose_name='Descrição das Atividades')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('current', models.BooleanField(default=False, verbose_name='Trabalho Atual')),
                ('company_url', models.URLField(blank=True, verbose_name='Site da Empresa')),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('title', models.CharField(max_length=200, verbose_name='Título/Cargo')),
                ('bio', models.TextField(verbose_name='Biografia')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Localização')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/', verbose_name='Foto do Perfil')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('website_url', models.URLField(blank=True, verbose_name='Website Pessoal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Projeto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('short_description', models.CharField(max_length=300, verbose_name='Descrição Curta')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Imagem do Projeto')),
                ('demo_url', models.URLField(blank=True, verbose_name='URL da Demo')),
                ('github_url', models.URLField(blank=True, verbose_name='URL do GitHub')),
                ('technologies', models.CharField(max_length=500, verbose_name='Tecnologias (separadas por vírgula)')),
                ('status', models.CharField(choices=[('completed', 'Concluído'), ('in_progress', 'Em Andamento'), ('planned', 'Planejado')], default='completed', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('featured', models.BooleanField(default=False, verbose_name='Projeto em Destaque')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-featured', 'order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Habilidade')),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Banco de Dados'), ('tools', 'Ferramentas'), ('other', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('proficiency', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Nível de Proficiência (%)')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícone (classe CSS)')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
